### ISSUE TITLE
Settings changes in the main (built-in) Wavelength Meter software overridden by settings in WLM_client 

### ISSUE THREAD

**Issue by OIST-EQuIP** [OIST-EQuIP/HighFinesse-Network#2]
For example, suppose the WLM_client is running on a machine B, and the User on machine B switches off CH1.
Subsequently if a different user goes to the server machine, and uses the HighFinesse program to switch on CH1, CH1 one will blink on temporarily before it is switched back off immediately.

The same issue happens for exposure settings: One cannot make modifications on the HighFinesse provided program that aren't overridden by the WLM_client settings.

EBK

**Comment by soon-teh** [comment]
Implemented as of [HighFinesse-Network@cda5226](https://github.com/OIST-EQuIP/HighFinesse-Network/commit/cda5226f66829f15206e07eb24c400f876f9f2da)
